'''
Created on Jan 5, 2017

@author: Alexandre Day
'''

import numpy as np

def data_to_binary(X,tmp_binfile="data.dat",delimiter=None):
    """
    Purpose:
        Writes it in binary format in default file 'data.dat' for tsne c++ exec. to use.
    """
    
    #print("Saving data in %s"%tmp_binfile)
    output_file=open(tmp_binfile,'wb')
    from array import array
    float_array = array('d', X.flatten())
    float_array.tofile(output_file)
    output_file.close()


def run_tsne_command_line(parameters,default_path="."):
    """
    Purpose:
        Run C++ exe from python with stdout output generated by exexutable printed to screen.
        By default the bh_tsne.exe should be in the current working directory
        This can be changed by choosing a different default_path
    """
    import subprocess
    param_str=[str(p) for p in parameters]
    subprocess.run([default_path+'/bh_tsne']+param_str)    
    
