'''
Created on Jan 5, 2017

@author: Alexandre Day
'''
import numpy as np

def data_to_binary(X,tmp_binfile="dev_bhtsne-master/.data.dat",delimiter=None):
    """
    Purpose:
        Writes it in binary format in default file 'cpp/.data.dat' for tsne c++ exec. to use.
    """
    print("Saving data in %s"%tmp_binfile)
    output_file=open(tmp_binfile,'wb')
    from array import array
    float_array = array('d', X.flatten())
    float_array.tofile(output_file)
    output_file.close()

def run_tsne_command_line(exec_path,parameters):
    """
    Purpose:
        Run C++ exe from python with stdout output generated by exexutable printed to screen.
    """
    import os
    param=str.join(" ",[str(p) for p in parameters])
    command=exec_path+" "+param
    print(command)
    os.system(command)
    #run_tsne_command_line("./dev_bhtsne-master/bh_tsne"+" "+[str(s) for s in parameters].join(" "))
    
    
    
    